/* onvifmediaMedia2BindingService.cpp
   Generated by gSOAP 2.8.22 from ./include/onvif.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "onvifmediaMedia2BindingService.h"

Media2BindingService::Media2BindingService()
{	Media2BindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

Media2BindingService::Media2BindingService(const struct soap &_soap) : soap(_soap)
{ }

Media2BindingService::Media2BindingService(soap_mode iomode)
{	Media2BindingService_init(iomode, iomode);
}

Media2BindingService::Media2BindingService(soap_mode imode, soap_mode omode)
{	Media2BindingService_init(imode, omode);
}

Media2BindingService::~Media2BindingService()
{ }

void Media2BindingService::Media2BindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"ns1", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void Media2BindingService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void Media2BindingService::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	Media2BindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
Media2BindingService *Media2BindingService::copy()
{	Media2BindingService *dup = SOAP_NEW_COPY(Media2BindingService(*(struct soap*)this));
	return dup;
}
#endif

int Media2BindingService::soap_close_socket()
{	return soap_closesock(this);
}

int Media2BindingService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int Media2BindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int Media2BindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int Media2BindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int Media2BindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void Media2BindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void Media2BindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *Media2BindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void Media2BindingService::soap_noheader()
{	this->header = NULL;
}

void Media2BindingService::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this);
	this->header->wsa5__MessageID = wsa5__MessageID;
	this->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->header->wsa5__From = wsa5__From;
	this->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->header->wsa5__FaultTo = wsa5__FaultTo;
	this->header->wsa5__To = wsa5__To;
	this->header->wsa5__Action = wsa5__Action;
	this->header->chan__ChannelInstance = chan__ChannelInstance;
	this->header->wsse__Security = wsse__Security;
}

const SOAP_ENV__Header *Media2BindingService::soap_header()
{	return this->header;
}

int Media2BindingService::run(int port)
{	if (soap_valid_socket(this->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				break;
			soap_destroy(this);
			soap_end(this);
		}
	}
	return this->error;
}

SOAP_SOCKET Media2BindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET Media2BindingService::accept()
{	return soap_accept(this);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int Media2BindingService::ssl_accept()
{	return soap_ssl_accept(this);
}
#endif

int Media2BindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___ns1__GetServiceCapabilities(Media2BindingService*);
static int serve___ns1__CreateProfile(Media2BindingService*);
static int serve___ns1__GetProfiles(Media2BindingService*);
static int serve___ns1__AddConfiguration(Media2BindingService*);
static int serve___ns1__RemoveConfiguration(Media2BindingService*);
static int serve___ns1__DeleteProfile(Media2BindingService*);
static int serve___ns1__GetVideoSourceConfigurations(Media2BindingService*);
static int serve___ns1__GetVideoEncoderConfigurations(Media2BindingService*);
static int serve___ns1__GetAudioSourceConfigurations(Media2BindingService*);
static int serve___ns1__GetAudioEncoderConfigurations(Media2BindingService*);
static int serve___ns1__GetAnalyticsConfigurations(Media2BindingService*);
static int serve___ns1__GetMetadataConfigurations(Media2BindingService*);
static int serve___ns1__GetAudioOutputConfigurations(Media2BindingService*);
static int serve___ns1__GetAudioDecoderConfigurations(Media2BindingService*);
static int serve___ns1__SetVideoSourceConfiguration(Media2BindingService*);
static int serve___ns1__SetVideoEncoderConfiguration(Media2BindingService*);
static int serve___ns1__SetAudioSourceConfiguration(Media2BindingService*);
static int serve___ns1__SetAudioEncoderConfiguration(Media2BindingService*);
static int serve___ns1__SetMetadataConfiguration(Media2BindingService*);
static int serve___ns1__SetAudioOutputConfiguration(Media2BindingService*);
static int serve___ns1__SetAudioDecoderConfiguration(Media2BindingService*);
static int serve___ns1__GetVideoSourceConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetVideoEncoderConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetAudioSourceConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetAudioEncoderConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetMetadataConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetAudioOutputConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetAudioDecoderConfigurationOptions(Media2BindingService*);
static int serve___ns1__GetVideoEncoderInstances(Media2BindingService*);
static int serve___ns1__GetStreamUri(Media2BindingService*);
static int serve___ns1__StartMulticastStreaming(Media2BindingService*);
static int serve___ns1__StopMulticastStreaming(Media2BindingService*);
static int serve___ns1__SetSynchronizationPoint(Media2BindingService*);
static int serve___ns1__GetSnapshotUri(Media2BindingService*);
static int serve___ns1__GetVideoSourceModes(Media2BindingService*);
static int serve___ns1__SetVideoSourceMode(Media2BindingService*);
static int serve___ns1__GetOSDs(Media2BindingService*);
static int serve___ns1__GetOSDOptions(Media2BindingService*);
static int serve___ns1__SetOSD(Media2BindingService*);
static int serve___ns1__CreateOSD(Media2BindingService*);
static int serve___ns1__DeleteOSD(Media2BindingService*);
static int serve___ns1__GetMasks(Media2BindingService*);
static int serve___ns1__GetMaskOptions(Media2BindingService*);
static int serve___ns1__SetMask(Media2BindingService*);
static int serve___ns1__CreateMask(Media2BindingService*);
static int serve___ns1__DeleteMask(Media2BindingService*);

int Media2BindingService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetServiceCapabilities"))
		return serve___ns1__GetServiceCapabilities(this);
	if (!soap_match_tag(this, this->tag, "ns1:CreateProfile"))
		return serve___ns1__CreateProfile(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetProfiles"))
		return serve___ns1__GetProfiles(this);
	if (!soap_match_tag(this, this->tag, "ns1:AddConfiguration"))
		return serve___ns1__AddConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:RemoveConfiguration"))
		return serve___ns1__RemoveConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:DeleteProfile"))
		return serve___ns1__DeleteProfile(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetVideoSourceConfigurations"))
		return serve___ns1__GetVideoSourceConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetVideoEncoderConfigurations"))
		return serve___ns1__GetVideoEncoderConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioSourceConfigurations"))
		return serve___ns1__GetAudioSourceConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioEncoderConfigurations"))
		return serve___ns1__GetAudioEncoderConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAnalyticsConfigurations"))
		return serve___ns1__GetAnalyticsConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetMetadataConfigurations"))
		return serve___ns1__GetMetadataConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioOutputConfigurations"))
		return serve___ns1__GetAudioOutputConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioDecoderConfigurations"))
		return serve___ns1__GetAudioDecoderConfigurations(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetVideoSourceConfiguration"))
		return serve___ns1__SetVideoSourceConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetVideoEncoderConfiguration"))
		return serve___ns1__SetVideoEncoderConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetAudioSourceConfiguration"))
		return serve___ns1__SetAudioSourceConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetAudioEncoderConfiguration"))
		return serve___ns1__SetAudioEncoderConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetMetadataConfiguration"))
		return serve___ns1__SetMetadataConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetAudioOutputConfiguration"))
		return serve___ns1__SetAudioOutputConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetAudioDecoderConfiguration"))
		return serve___ns1__SetAudioDecoderConfiguration(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetVideoSourceConfigurationOptions"))
		return serve___ns1__GetVideoSourceConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetVideoEncoderConfigurationOptions"))
		return serve___ns1__GetVideoEncoderConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioSourceConfigurationOptions"))
		return serve___ns1__GetAudioSourceConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioEncoderConfigurationOptions"))
		return serve___ns1__GetAudioEncoderConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetMetadataConfigurationOptions"))
		return serve___ns1__GetMetadataConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioOutputConfigurationOptions"))
		return serve___ns1__GetAudioOutputConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetAudioDecoderConfigurationOptions"))
		return serve___ns1__GetAudioDecoderConfigurationOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetVideoEncoderInstances"))
		return serve___ns1__GetVideoEncoderInstances(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetStreamUri"))
		return serve___ns1__GetStreamUri(this);
	if (!soap_match_tag(this, this->tag, "ns1:StartMulticastStreaming"))
		return serve___ns1__StartMulticastStreaming(this);
	if (!soap_match_tag(this, this->tag, "ns1:StopMulticastStreaming"))
		return serve___ns1__StopMulticastStreaming(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetSynchronizationPoint"))
		return serve___ns1__SetSynchronizationPoint(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetSnapshotUri"))
		return serve___ns1__GetSnapshotUri(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetVideoSourceModes"))
		return serve___ns1__GetVideoSourceModes(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetVideoSourceMode"))
		return serve___ns1__SetVideoSourceMode(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetOSDs"))
		return serve___ns1__GetOSDs(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetOSDOptions"))
		return serve___ns1__GetOSDOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetOSD"))
		return serve___ns1__SetOSD(this);
	if (!soap_match_tag(this, this->tag, "ns1:CreateOSD"))
		return serve___ns1__CreateOSD(this);
	if (!soap_match_tag(this, this->tag, "ns1:DeleteOSD"))
		return serve___ns1__DeleteOSD(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetMasks"))
		return serve___ns1__GetMasks(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetMaskOptions"))
		return serve___ns1__GetMaskOptions(this);
	if (!soap_match_tag(this, this->tag, "ns1:SetMask"))
		return serve___ns1__SetMask(this);
	if (!soap_match_tag(this, this->tag, "ns1:CreateMask"))
		return serve___ns1__CreateMask(this);
	if (!soap_match_tag(this, this->tag, "ns1:DeleteMask"))
		return serve___ns1__DeleteMask(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve___ns1__GetServiceCapabilities(Media2BindingService *soap)
{	struct __ns1__GetServiceCapabilities soap_tmp___ns1__GetServiceCapabilities;
	_ns1__GetServiceCapabilitiesResponse ns1__GetServiceCapabilitiesResponse;
	ns1__GetServiceCapabilitiesResponse.soap_default(soap);
	soap_default___ns1__GetServiceCapabilities(soap, &soap_tmp___ns1__GetServiceCapabilities);
	if (!soap_get___ns1__GetServiceCapabilities(soap, &soap_tmp___ns1__GetServiceCapabilities, "-ns1:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetServiceCapabilities(soap_tmp___ns1__GetServiceCapabilities.ns1__GetServiceCapabilities, ns1__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetServiceCapabilitiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetServiceCapabilitiesResponse.soap_put(soap, "ns1:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetServiceCapabilitiesResponse.soap_put(soap, "ns1:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__CreateProfile(Media2BindingService *soap)
{	struct __ns1__CreateProfile soap_tmp___ns1__CreateProfile;
	_ns1__CreateProfileResponse ns1__CreateProfileResponse;
	ns1__CreateProfileResponse.soap_default(soap);
	soap_default___ns1__CreateProfile(soap, &soap_tmp___ns1__CreateProfile);
	if (!soap_get___ns1__CreateProfile(soap, &soap_tmp___ns1__CreateProfile, "-ns1:CreateProfile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CreateProfile(soap_tmp___ns1__CreateProfile.ns1__CreateProfile, ns1__CreateProfileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__CreateProfileResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CreateProfileResponse.soap_put(soap, "ns1:CreateProfileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CreateProfileResponse.soap_put(soap, "ns1:CreateProfileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetProfiles(Media2BindingService *soap)
{	struct __ns1__GetProfiles soap_tmp___ns1__GetProfiles;
	_ns1__GetProfilesResponse ns1__GetProfilesResponse;
	ns1__GetProfilesResponse.soap_default(soap);
	soap_default___ns1__GetProfiles(soap, &soap_tmp___ns1__GetProfiles);
	if (!soap_get___ns1__GetProfiles(soap, &soap_tmp___ns1__GetProfiles, "-ns1:GetProfiles", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetProfiles(soap_tmp___ns1__GetProfiles.ns1__GetProfiles, ns1__GetProfilesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetProfilesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetProfilesResponse.soap_put(soap, "ns1:GetProfilesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetProfilesResponse.soap_put(soap, "ns1:GetProfilesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__AddConfiguration(Media2BindingService *soap)
{	struct __ns1__AddConfiguration soap_tmp___ns1__AddConfiguration;
	_ns1__AddConfigurationResponse ns1__AddConfigurationResponse;
	ns1__AddConfigurationResponse.soap_default(soap);
	soap_default___ns1__AddConfiguration(soap, &soap_tmp___ns1__AddConfiguration);
	if (!soap_get___ns1__AddConfiguration(soap, &soap_tmp___ns1__AddConfiguration, "-ns1:AddConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->AddConfiguration(soap_tmp___ns1__AddConfiguration.ns1__AddConfiguration, ns1__AddConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__AddConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__AddConfigurationResponse.soap_put(soap, "ns1:AddConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__AddConfigurationResponse.soap_put(soap, "ns1:AddConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__RemoveConfiguration(Media2BindingService *soap)
{	struct __ns1__RemoveConfiguration soap_tmp___ns1__RemoveConfiguration;
	_ns1__RemoveConfigurationResponse ns1__RemoveConfigurationResponse;
	ns1__RemoveConfigurationResponse.soap_default(soap);
	soap_default___ns1__RemoveConfiguration(soap, &soap_tmp___ns1__RemoveConfiguration);
	if (!soap_get___ns1__RemoveConfiguration(soap, &soap_tmp___ns1__RemoveConfiguration, "-ns1:RemoveConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->RemoveConfiguration(soap_tmp___ns1__RemoveConfiguration.ns1__RemoveConfiguration, ns1__RemoveConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__RemoveConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__RemoveConfigurationResponse.soap_put(soap, "ns1:RemoveConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__RemoveConfigurationResponse.soap_put(soap, "ns1:RemoveConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__DeleteProfile(Media2BindingService *soap)
{	struct __ns1__DeleteProfile soap_tmp___ns1__DeleteProfile;
	_ns1__DeleteProfileResponse ns1__DeleteProfileResponse;
	ns1__DeleteProfileResponse.soap_default(soap);
	soap_default___ns1__DeleteProfile(soap, &soap_tmp___ns1__DeleteProfile);
	if (!soap_get___ns1__DeleteProfile(soap, &soap_tmp___ns1__DeleteProfile, "-ns1:DeleteProfile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->DeleteProfile(soap_tmp___ns1__DeleteProfile.ns1__DeleteProfile, ns1__DeleteProfileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__DeleteProfileResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__DeleteProfileResponse.soap_put(soap, "ns1:DeleteProfileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__DeleteProfileResponse.soap_put(soap, "ns1:DeleteProfileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetVideoSourceConfigurations(Media2BindingService *soap)
{	struct __ns1__GetVideoSourceConfigurations soap_tmp___ns1__GetVideoSourceConfigurations;
	_ns1__GetVideoSourceConfigurationsResponse ns1__GetVideoSourceConfigurationsResponse;
	ns1__GetVideoSourceConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetVideoSourceConfigurations(soap, &soap_tmp___ns1__GetVideoSourceConfigurations);
	if (!soap_get___ns1__GetVideoSourceConfigurations(soap, &soap_tmp___ns1__GetVideoSourceConfigurations, "-ns1:GetVideoSourceConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetVideoSourceConfigurations(soap_tmp___ns1__GetVideoSourceConfigurations.ns1__GetVideoSourceConfigurations, ns1__GetVideoSourceConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetVideoSourceConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetVideoSourceConfigurationsResponse.soap_put(soap, "ns1:GetVideoSourceConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetVideoSourceConfigurationsResponse.soap_put(soap, "ns1:GetVideoSourceConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetVideoEncoderConfigurations(Media2BindingService *soap)
{	struct __ns1__GetVideoEncoderConfigurations soap_tmp___ns1__GetVideoEncoderConfigurations;
	_ns1__GetVideoEncoderConfigurationsResponse ns1__GetVideoEncoderConfigurationsResponse;
	ns1__GetVideoEncoderConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetVideoEncoderConfigurations(soap, &soap_tmp___ns1__GetVideoEncoderConfigurations);
	if (!soap_get___ns1__GetVideoEncoderConfigurations(soap, &soap_tmp___ns1__GetVideoEncoderConfigurations, "-ns1:GetVideoEncoderConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetVideoEncoderConfigurations(soap_tmp___ns1__GetVideoEncoderConfigurations.ns1__GetVideoEncoderConfigurations, ns1__GetVideoEncoderConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetVideoEncoderConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetVideoEncoderConfigurationsResponse.soap_put(soap, "ns1:GetVideoEncoderConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetVideoEncoderConfigurationsResponse.soap_put(soap, "ns1:GetVideoEncoderConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioSourceConfigurations(Media2BindingService *soap)
{	struct __ns1__GetAudioSourceConfigurations soap_tmp___ns1__GetAudioSourceConfigurations;
	_ns1__GetAudioSourceConfigurationsResponse ns1__GetAudioSourceConfigurationsResponse;
	ns1__GetAudioSourceConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetAudioSourceConfigurations(soap, &soap_tmp___ns1__GetAudioSourceConfigurations);
	if (!soap_get___ns1__GetAudioSourceConfigurations(soap, &soap_tmp___ns1__GetAudioSourceConfigurations, "-ns1:GetAudioSourceConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioSourceConfigurations(soap_tmp___ns1__GetAudioSourceConfigurations.ns1__GetAudioSourceConfigurations, ns1__GetAudioSourceConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioSourceConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioSourceConfigurationsResponse.soap_put(soap, "ns1:GetAudioSourceConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioSourceConfigurationsResponse.soap_put(soap, "ns1:GetAudioSourceConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioEncoderConfigurations(Media2BindingService *soap)
{	struct __ns1__GetAudioEncoderConfigurations soap_tmp___ns1__GetAudioEncoderConfigurations;
	_ns1__GetAudioEncoderConfigurationsResponse ns1__GetAudioEncoderConfigurationsResponse;
	ns1__GetAudioEncoderConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetAudioEncoderConfigurations(soap, &soap_tmp___ns1__GetAudioEncoderConfigurations);
	if (!soap_get___ns1__GetAudioEncoderConfigurations(soap, &soap_tmp___ns1__GetAudioEncoderConfigurations, "-ns1:GetAudioEncoderConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioEncoderConfigurations(soap_tmp___ns1__GetAudioEncoderConfigurations.ns1__GetAudioEncoderConfigurations, ns1__GetAudioEncoderConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioEncoderConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioEncoderConfigurationsResponse.soap_put(soap, "ns1:GetAudioEncoderConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioEncoderConfigurationsResponse.soap_put(soap, "ns1:GetAudioEncoderConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAnalyticsConfigurations(Media2BindingService *soap)
{	struct __ns1__GetAnalyticsConfigurations soap_tmp___ns1__GetAnalyticsConfigurations;
	_ns1__GetAnalyticsConfigurationsResponse ns1__GetAnalyticsConfigurationsResponse;
	ns1__GetAnalyticsConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetAnalyticsConfigurations(soap, &soap_tmp___ns1__GetAnalyticsConfigurations);
	if (!soap_get___ns1__GetAnalyticsConfigurations(soap, &soap_tmp___ns1__GetAnalyticsConfigurations, "-ns1:GetAnalyticsConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAnalyticsConfigurations(soap_tmp___ns1__GetAnalyticsConfigurations.ns1__GetAnalyticsConfigurations, ns1__GetAnalyticsConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAnalyticsConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAnalyticsConfigurationsResponse.soap_put(soap, "ns1:GetAnalyticsConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAnalyticsConfigurationsResponse.soap_put(soap, "ns1:GetAnalyticsConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetMetadataConfigurations(Media2BindingService *soap)
{	struct __ns1__GetMetadataConfigurations soap_tmp___ns1__GetMetadataConfigurations;
	_ns1__GetMetadataConfigurationsResponse ns1__GetMetadataConfigurationsResponse;
	ns1__GetMetadataConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetMetadataConfigurations(soap, &soap_tmp___ns1__GetMetadataConfigurations);
	if (!soap_get___ns1__GetMetadataConfigurations(soap, &soap_tmp___ns1__GetMetadataConfigurations, "-ns1:GetMetadataConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetMetadataConfigurations(soap_tmp___ns1__GetMetadataConfigurations.ns1__GetMetadataConfigurations, ns1__GetMetadataConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetMetadataConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetMetadataConfigurationsResponse.soap_put(soap, "ns1:GetMetadataConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetMetadataConfigurationsResponse.soap_put(soap, "ns1:GetMetadataConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioOutputConfigurations(Media2BindingService *soap)
{	struct __ns1__GetAudioOutputConfigurations soap_tmp___ns1__GetAudioOutputConfigurations;
	_ns1__GetAudioOutputConfigurationsResponse ns1__GetAudioOutputConfigurationsResponse;
	ns1__GetAudioOutputConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetAudioOutputConfigurations(soap, &soap_tmp___ns1__GetAudioOutputConfigurations);
	if (!soap_get___ns1__GetAudioOutputConfigurations(soap, &soap_tmp___ns1__GetAudioOutputConfigurations, "-ns1:GetAudioOutputConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioOutputConfigurations(soap_tmp___ns1__GetAudioOutputConfigurations.ns1__GetAudioOutputConfigurations, ns1__GetAudioOutputConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioOutputConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioOutputConfigurationsResponse.soap_put(soap, "ns1:GetAudioOutputConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioOutputConfigurationsResponse.soap_put(soap, "ns1:GetAudioOutputConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioDecoderConfigurations(Media2BindingService *soap)
{	struct __ns1__GetAudioDecoderConfigurations soap_tmp___ns1__GetAudioDecoderConfigurations;
	_ns1__GetAudioDecoderConfigurationsResponse ns1__GetAudioDecoderConfigurationsResponse;
	ns1__GetAudioDecoderConfigurationsResponse.soap_default(soap);
	soap_default___ns1__GetAudioDecoderConfigurations(soap, &soap_tmp___ns1__GetAudioDecoderConfigurations);
	if (!soap_get___ns1__GetAudioDecoderConfigurations(soap, &soap_tmp___ns1__GetAudioDecoderConfigurations, "-ns1:GetAudioDecoderConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioDecoderConfigurations(soap_tmp___ns1__GetAudioDecoderConfigurations.ns1__GetAudioDecoderConfigurations, ns1__GetAudioDecoderConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioDecoderConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioDecoderConfigurationsResponse.soap_put(soap, "ns1:GetAudioDecoderConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioDecoderConfigurationsResponse.soap_put(soap, "ns1:GetAudioDecoderConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetVideoSourceConfiguration(Media2BindingService *soap)
{	struct __ns1__SetVideoSourceConfiguration soap_tmp___ns1__SetVideoSourceConfiguration;
	struct __ns1__SetVideoSourceConfigurationResponse soap_tmp___ns1__SetVideoSourceConfigurationResponse;
	soap_default___ns1__SetVideoSourceConfigurationResponse(soap, &soap_tmp___ns1__SetVideoSourceConfigurationResponse);
	soap_default___ns1__SetVideoSourceConfiguration(soap, &soap_tmp___ns1__SetVideoSourceConfiguration);
	if (!soap_get___ns1__SetVideoSourceConfiguration(soap, &soap_tmp___ns1__SetVideoSourceConfiguration, "-ns1:SetVideoSourceConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetVideoSourceConfiguration(soap_tmp___ns1__SetVideoSourceConfiguration.ns1__SetVideoSourceConfiguration, soap_tmp___ns1__SetVideoSourceConfigurationResponse.ns1__SetVideoSourceConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetVideoSourceConfigurationResponse(soap, &soap_tmp___ns1__SetVideoSourceConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetVideoSourceConfigurationResponse(soap, &soap_tmp___ns1__SetVideoSourceConfigurationResponse, "-ns1:SetVideoSourceConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetVideoSourceConfigurationResponse(soap, &soap_tmp___ns1__SetVideoSourceConfigurationResponse, "-ns1:SetVideoSourceConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetVideoEncoderConfiguration(Media2BindingService *soap)
{	struct __ns1__SetVideoEncoderConfiguration soap_tmp___ns1__SetVideoEncoderConfiguration;
	struct __ns1__SetVideoEncoderConfigurationResponse soap_tmp___ns1__SetVideoEncoderConfigurationResponse;
	soap_default___ns1__SetVideoEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetVideoEncoderConfigurationResponse);
	soap_default___ns1__SetVideoEncoderConfiguration(soap, &soap_tmp___ns1__SetVideoEncoderConfiguration);
	if (!soap_get___ns1__SetVideoEncoderConfiguration(soap, &soap_tmp___ns1__SetVideoEncoderConfiguration, "-ns1:SetVideoEncoderConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetVideoEncoderConfiguration(soap_tmp___ns1__SetVideoEncoderConfiguration.ns1__SetVideoEncoderConfiguration, soap_tmp___ns1__SetVideoEncoderConfigurationResponse.ns1__SetVideoEncoderConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetVideoEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetVideoEncoderConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetVideoEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetVideoEncoderConfigurationResponse, "-ns1:SetVideoEncoderConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetVideoEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetVideoEncoderConfigurationResponse, "-ns1:SetVideoEncoderConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetAudioSourceConfiguration(Media2BindingService *soap)
{	struct __ns1__SetAudioSourceConfiguration soap_tmp___ns1__SetAudioSourceConfiguration;
	struct __ns1__SetAudioSourceConfigurationResponse soap_tmp___ns1__SetAudioSourceConfigurationResponse;
	soap_default___ns1__SetAudioSourceConfigurationResponse(soap, &soap_tmp___ns1__SetAudioSourceConfigurationResponse);
	soap_default___ns1__SetAudioSourceConfiguration(soap, &soap_tmp___ns1__SetAudioSourceConfiguration);
	if (!soap_get___ns1__SetAudioSourceConfiguration(soap, &soap_tmp___ns1__SetAudioSourceConfiguration, "-ns1:SetAudioSourceConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetAudioSourceConfiguration(soap_tmp___ns1__SetAudioSourceConfiguration.ns1__SetAudioSourceConfiguration, soap_tmp___ns1__SetAudioSourceConfigurationResponse.ns1__SetAudioSourceConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetAudioSourceConfigurationResponse(soap, &soap_tmp___ns1__SetAudioSourceConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetAudioSourceConfigurationResponse(soap, &soap_tmp___ns1__SetAudioSourceConfigurationResponse, "-ns1:SetAudioSourceConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetAudioSourceConfigurationResponse(soap, &soap_tmp___ns1__SetAudioSourceConfigurationResponse, "-ns1:SetAudioSourceConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetAudioEncoderConfiguration(Media2BindingService *soap)
{	struct __ns1__SetAudioEncoderConfiguration soap_tmp___ns1__SetAudioEncoderConfiguration;
	struct __ns1__SetAudioEncoderConfigurationResponse soap_tmp___ns1__SetAudioEncoderConfigurationResponse;
	soap_default___ns1__SetAudioEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioEncoderConfigurationResponse);
	soap_default___ns1__SetAudioEncoderConfiguration(soap, &soap_tmp___ns1__SetAudioEncoderConfiguration);
	if (!soap_get___ns1__SetAudioEncoderConfiguration(soap, &soap_tmp___ns1__SetAudioEncoderConfiguration, "-ns1:SetAudioEncoderConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetAudioEncoderConfiguration(soap_tmp___ns1__SetAudioEncoderConfiguration.ns1__SetAudioEncoderConfiguration, soap_tmp___ns1__SetAudioEncoderConfigurationResponse.ns1__SetAudioEncoderConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetAudioEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioEncoderConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetAudioEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioEncoderConfigurationResponse, "-ns1:SetAudioEncoderConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetAudioEncoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioEncoderConfigurationResponse, "-ns1:SetAudioEncoderConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetMetadataConfiguration(Media2BindingService *soap)
{	struct __ns1__SetMetadataConfiguration soap_tmp___ns1__SetMetadataConfiguration;
	struct __ns1__SetMetadataConfigurationResponse soap_tmp___ns1__SetMetadataConfigurationResponse;
	soap_default___ns1__SetMetadataConfigurationResponse(soap, &soap_tmp___ns1__SetMetadataConfigurationResponse);
	soap_default___ns1__SetMetadataConfiguration(soap, &soap_tmp___ns1__SetMetadataConfiguration);
	if (!soap_get___ns1__SetMetadataConfiguration(soap, &soap_tmp___ns1__SetMetadataConfiguration, "-ns1:SetMetadataConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetMetadataConfiguration(soap_tmp___ns1__SetMetadataConfiguration.ns1__SetMetadataConfiguration, soap_tmp___ns1__SetMetadataConfigurationResponse.ns1__SetMetadataConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetMetadataConfigurationResponse(soap, &soap_tmp___ns1__SetMetadataConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetMetadataConfigurationResponse(soap, &soap_tmp___ns1__SetMetadataConfigurationResponse, "-ns1:SetMetadataConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetMetadataConfigurationResponse(soap, &soap_tmp___ns1__SetMetadataConfigurationResponse, "-ns1:SetMetadataConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetAudioOutputConfiguration(Media2BindingService *soap)
{	struct __ns1__SetAudioOutputConfiguration soap_tmp___ns1__SetAudioOutputConfiguration;
	struct __ns1__SetAudioOutputConfigurationResponse soap_tmp___ns1__SetAudioOutputConfigurationResponse;
	soap_default___ns1__SetAudioOutputConfigurationResponse(soap, &soap_tmp___ns1__SetAudioOutputConfigurationResponse);
	soap_default___ns1__SetAudioOutputConfiguration(soap, &soap_tmp___ns1__SetAudioOutputConfiguration);
	if (!soap_get___ns1__SetAudioOutputConfiguration(soap, &soap_tmp___ns1__SetAudioOutputConfiguration, "-ns1:SetAudioOutputConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetAudioOutputConfiguration(soap_tmp___ns1__SetAudioOutputConfiguration.ns1__SetAudioOutputConfiguration, soap_tmp___ns1__SetAudioOutputConfigurationResponse.ns1__SetAudioOutputConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetAudioOutputConfigurationResponse(soap, &soap_tmp___ns1__SetAudioOutputConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetAudioOutputConfigurationResponse(soap, &soap_tmp___ns1__SetAudioOutputConfigurationResponse, "-ns1:SetAudioOutputConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetAudioOutputConfigurationResponse(soap, &soap_tmp___ns1__SetAudioOutputConfigurationResponse, "-ns1:SetAudioOutputConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetAudioDecoderConfiguration(Media2BindingService *soap)
{	struct __ns1__SetAudioDecoderConfiguration soap_tmp___ns1__SetAudioDecoderConfiguration;
	struct __ns1__SetAudioDecoderConfigurationResponse soap_tmp___ns1__SetAudioDecoderConfigurationResponse;
	soap_default___ns1__SetAudioDecoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioDecoderConfigurationResponse);
	soap_default___ns1__SetAudioDecoderConfiguration(soap, &soap_tmp___ns1__SetAudioDecoderConfiguration);
	if (!soap_get___ns1__SetAudioDecoderConfiguration(soap, &soap_tmp___ns1__SetAudioDecoderConfiguration, "-ns1:SetAudioDecoderConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetAudioDecoderConfiguration(soap_tmp___ns1__SetAudioDecoderConfiguration.ns1__SetAudioDecoderConfiguration, soap_tmp___ns1__SetAudioDecoderConfigurationResponse.ns1__SetAudioDecoderConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetAudioDecoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioDecoderConfigurationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetAudioDecoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioDecoderConfigurationResponse, "-ns1:SetAudioDecoderConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetAudioDecoderConfigurationResponse(soap, &soap_tmp___ns1__SetAudioDecoderConfigurationResponse, "-ns1:SetAudioDecoderConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetVideoSourceConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetVideoSourceConfigurationOptions soap_tmp___ns1__GetVideoSourceConfigurationOptions;
	_ns1__GetVideoSourceConfigurationOptionsResponse ns1__GetVideoSourceConfigurationOptionsResponse;
	ns1__GetVideoSourceConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetVideoSourceConfigurationOptions(soap, &soap_tmp___ns1__GetVideoSourceConfigurationOptions);
	if (!soap_get___ns1__GetVideoSourceConfigurationOptions(soap, &soap_tmp___ns1__GetVideoSourceConfigurationOptions, "-ns1:GetVideoSourceConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetVideoSourceConfigurationOptions(soap_tmp___ns1__GetVideoSourceConfigurationOptions.ns1__GetVideoSourceConfigurationOptions, ns1__GetVideoSourceConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetVideoSourceConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetVideoSourceConfigurationOptionsResponse.soap_put(soap, "ns1:GetVideoSourceConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetVideoSourceConfigurationOptionsResponse.soap_put(soap, "ns1:GetVideoSourceConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetVideoEncoderConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetVideoEncoderConfigurationOptions soap_tmp___ns1__GetVideoEncoderConfigurationOptions;
	_ns1__GetVideoEncoderConfigurationOptionsResponse ns1__GetVideoEncoderConfigurationOptionsResponse;
	ns1__GetVideoEncoderConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetVideoEncoderConfigurationOptions(soap, &soap_tmp___ns1__GetVideoEncoderConfigurationOptions);
	if (!soap_get___ns1__GetVideoEncoderConfigurationOptions(soap, &soap_tmp___ns1__GetVideoEncoderConfigurationOptions, "-ns1:GetVideoEncoderConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetVideoEncoderConfigurationOptions(soap_tmp___ns1__GetVideoEncoderConfigurationOptions.ns1__GetVideoEncoderConfigurationOptions, ns1__GetVideoEncoderConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetVideoEncoderConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetVideoEncoderConfigurationOptionsResponse.soap_put(soap, "ns1:GetVideoEncoderConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetVideoEncoderConfigurationOptionsResponse.soap_put(soap, "ns1:GetVideoEncoderConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioSourceConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetAudioSourceConfigurationOptions soap_tmp___ns1__GetAudioSourceConfigurationOptions;
	_ns1__GetAudioSourceConfigurationOptionsResponse ns1__GetAudioSourceConfigurationOptionsResponse;
	ns1__GetAudioSourceConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetAudioSourceConfigurationOptions(soap, &soap_tmp___ns1__GetAudioSourceConfigurationOptions);
	if (!soap_get___ns1__GetAudioSourceConfigurationOptions(soap, &soap_tmp___ns1__GetAudioSourceConfigurationOptions, "-ns1:GetAudioSourceConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioSourceConfigurationOptions(soap_tmp___ns1__GetAudioSourceConfigurationOptions.ns1__GetAudioSourceConfigurationOptions, ns1__GetAudioSourceConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioSourceConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioSourceConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioSourceConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioSourceConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioSourceConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioEncoderConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetAudioEncoderConfigurationOptions soap_tmp___ns1__GetAudioEncoderConfigurationOptions;
	_ns1__GetAudioEncoderConfigurationOptionsResponse ns1__GetAudioEncoderConfigurationOptionsResponse;
	ns1__GetAudioEncoderConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetAudioEncoderConfigurationOptions(soap, &soap_tmp___ns1__GetAudioEncoderConfigurationOptions);
	if (!soap_get___ns1__GetAudioEncoderConfigurationOptions(soap, &soap_tmp___ns1__GetAudioEncoderConfigurationOptions, "-ns1:GetAudioEncoderConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioEncoderConfigurationOptions(soap_tmp___ns1__GetAudioEncoderConfigurationOptions.ns1__GetAudioEncoderConfigurationOptions, ns1__GetAudioEncoderConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioEncoderConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioEncoderConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioEncoderConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioEncoderConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioEncoderConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetMetadataConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetMetadataConfigurationOptions soap_tmp___ns1__GetMetadataConfigurationOptions;
	_ns1__GetMetadataConfigurationOptionsResponse ns1__GetMetadataConfigurationOptionsResponse;
	ns1__GetMetadataConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetMetadataConfigurationOptions(soap, &soap_tmp___ns1__GetMetadataConfigurationOptions);
	if (!soap_get___ns1__GetMetadataConfigurationOptions(soap, &soap_tmp___ns1__GetMetadataConfigurationOptions, "-ns1:GetMetadataConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetMetadataConfigurationOptions(soap_tmp___ns1__GetMetadataConfigurationOptions.ns1__GetMetadataConfigurationOptions, ns1__GetMetadataConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetMetadataConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetMetadataConfigurationOptionsResponse.soap_put(soap, "ns1:GetMetadataConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetMetadataConfigurationOptionsResponse.soap_put(soap, "ns1:GetMetadataConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioOutputConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetAudioOutputConfigurationOptions soap_tmp___ns1__GetAudioOutputConfigurationOptions;
	_ns1__GetAudioOutputConfigurationOptionsResponse ns1__GetAudioOutputConfigurationOptionsResponse;
	ns1__GetAudioOutputConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetAudioOutputConfigurationOptions(soap, &soap_tmp___ns1__GetAudioOutputConfigurationOptions);
	if (!soap_get___ns1__GetAudioOutputConfigurationOptions(soap, &soap_tmp___ns1__GetAudioOutputConfigurationOptions, "-ns1:GetAudioOutputConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioOutputConfigurationOptions(soap_tmp___ns1__GetAudioOutputConfigurationOptions.ns1__GetAudioOutputConfigurationOptions, ns1__GetAudioOutputConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioOutputConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioOutputConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioOutputConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioOutputConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioOutputConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetAudioDecoderConfigurationOptions(Media2BindingService *soap)
{	struct __ns1__GetAudioDecoderConfigurationOptions soap_tmp___ns1__GetAudioDecoderConfigurationOptions;
	_ns1__GetAudioDecoderConfigurationOptionsResponse ns1__GetAudioDecoderConfigurationOptionsResponse;
	ns1__GetAudioDecoderConfigurationOptionsResponse.soap_default(soap);
	soap_default___ns1__GetAudioDecoderConfigurationOptions(soap, &soap_tmp___ns1__GetAudioDecoderConfigurationOptions);
	if (!soap_get___ns1__GetAudioDecoderConfigurationOptions(soap, &soap_tmp___ns1__GetAudioDecoderConfigurationOptions, "-ns1:GetAudioDecoderConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetAudioDecoderConfigurationOptions(soap_tmp___ns1__GetAudioDecoderConfigurationOptions.ns1__GetAudioDecoderConfigurationOptions, ns1__GetAudioDecoderConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAudioDecoderConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAudioDecoderConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioDecoderConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAudioDecoderConfigurationOptionsResponse.soap_put(soap, "ns1:GetAudioDecoderConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetVideoEncoderInstances(Media2BindingService *soap)
{	struct __ns1__GetVideoEncoderInstances soap_tmp___ns1__GetVideoEncoderInstances;
	_ns1__GetVideoEncoderInstancesResponse ns1__GetVideoEncoderInstancesResponse;
	ns1__GetVideoEncoderInstancesResponse.soap_default(soap);
	soap_default___ns1__GetVideoEncoderInstances(soap, &soap_tmp___ns1__GetVideoEncoderInstances);
	if (!soap_get___ns1__GetVideoEncoderInstances(soap, &soap_tmp___ns1__GetVideoEncoderInstances, "-ns1:GetVideoEncoderInstances", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetVideoEncoderInstances(soap_tmp___ns1__GetVideoEncoderInstances.ns1__GetVideoEncoderInstances, ns1__GetVideoEncoderInstancesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetVideoEncoderInstancesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetVideoEncoderInstancesResponse.soap_put(soap, "ns1:GetVideoEncoderInstancesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetVideoEncoderInstancesResponse.soap_put(soap, "ns1:GetVideoEncoderInstancesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetStreamUri(Media2BindingService *soap)
{	struct __ns1__GetStreamUri soap_tmp___ns1__GetStreamUri;
	_ns1__GetStreamUriResponse ns1__GetStreamUriResponse;
	ns1__GetStreamUriResponse.soap_default(soap);
	soap_default___ns1__GetStreamUri(soap, &soap_tmp___ns1__GetStreamUri);
	if (!soap_get___ns1__GetStreamUri(soap, &soap_tmp___ns1__GetStreamUri, "-ns1:GetStreamUri", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetStreamUri(soap_tmp___ns1__GetStreamUri.ns1__GetStreamUri, ns1__GetStreamUriResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetStreamUriResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetStreamUriResponse.soap_put(soap, "ns1:GetStreamUriResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetStreamUriResponse.soap_put(soap, "ns1:GetStreamUriResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__StartMulticastStreaming(Media2BindingService *soap)
{	struct __ns1__StartMulticastStreaming soap_tmp___ns1__StartMulticastStreaming;
	struct __ns1__StartMulticastStreamingResponse soap_tmp___ns1__StartMulticastStreamingResponse;
	soap_default___ns1__StartMulticastStreamingResponse(soap, &soap_tmp___ns1__StartMulticastStreamingResponse);
	soap_default___ns1__StartMulticastStreaming(soap, &soap_tmp___ns1__StartMulticastStreaming);
	if (!soap_get___ns1__StartMulticastStreaming(soap, &soap_tmp___ns1__StartMulticastStreaming, "-ns1:StartMulticastStreaming", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->StartMulticastStreaming(soap_tmp___ns1__StartMulticastStreaming.ns1__StartMulticastStreaming, soap_tmp___ns1__StartMulticastStreamingResponse.ns1__StartMulticastStreamingResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__StartMulticastStreamingResponse(soap, &soap_tmp___ns1__StartMulticastStreamingResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__StartMulticastStreamingResponse(soap, &soap_tmp___ns1__StartMulticastStreamingResponse, "-ns1:StartMulticastStreamingResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__StartMulticastStreamingResponse(soap, &soap_tmp___ns1__StartMulticastStreamingResponse, "-ns1:StartMulticastStreamingResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__StopMulticastStreaming(Media2BindingService *soap)
{	struct __ns1__StopMulticastStreaming soap_tmp___ns1__StopMulticastStreaming;
	struct __ns1__StopMulticastStreamingResponse soap_tmp___ns1__StopMulticastStreamingResponse;
	soap_default___ns1__StopMulticastStreamingResponse(soap, &soap_tmp___ns1__StopMulticastStreamingResponse);
	soap_default___ns1__StopMulticastStreaming(soap, &soap_tmp___ns1__StopMulticastStreaming);
	if (!soap_get___ns1__StopMulticastStreaming(soap, &soap_tmp___ns1__StopMulticastStreaming, "-ns1:StopMulticastStreaming", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->StopMulticastStreaming(soap_tmp___ns1__StopMulticastStreaming.ns1__StopMulticastStreaming, soap_tmp___ns1__StopMulticastStreamingResponse.ns1__StopMulticastStreamingResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__StopMulticastStreamingResponse(soap, &soap_tmp___ns1__StopMulticastStreamingResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__StopMulticastStreamingResponse(soap, &soap_tmp___ns1__StopMulticastStreamingResponse, "-ns1:StopMulticastStreamingResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__StopMulticastStreamingResponse(soap, &soap_tmp___ns1__StopMulticastStreamingResponse, "-ns1:StopMulticastStreamingResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetSynchronizationPoint(Media2BindingService *soap)
{	struct __ns1__SetSynchronizationPoint soap_tmp___ns1__SetSynchronizationPoint;
	_ns1__SetSynchronizationPointResponse ns1__SetSynchronizationPointResponse;
	ns1__SetSynchronizationPointResponse.soap_default(soap);
	soap_default___ns1__SetSynchronizationPoint(soap, &soap_tmp___ns1__SetSynchronizationPoint);
	if (!soap_get___ns1__SetSynchronizationPoint(soap, &soap_tmp___ns1__SetSynchronizationPoint, "-ns1:SetSynchronizationPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetSynchronizationPoint(soap_tmp___ns1__SetSynchronizationPoint.ns1__SetSynchronizationPoint, ns1__SetSynchronizationPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__SetSynchronizationPointResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SetSynchronizationPointResponse.soap_put(soap, "ns1:SetSynchronizationPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SetSynchronizationPointResponse.soap_put(soap, "ns1:SetSynchronizationPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetSnapshotUri(Media2BindingService *soap)
{	struct __ns1__GetSnapshotUri soap_tmp___ns1__GetSnapshotUri;
	_ns1__GetSnapshotUriResponse ns1__GetSnapshotUriResponse;
	ns1__GetSnapshotUriResponse.soap_default(soap);
	soap_default___ns1__GetSnapshotUri(soap, &soap_tmp___ns1__GetSnapshotUri);
	if (!soap_get___ns1__GetSnapshotUri(soap, &soap_tmp___ns1__GetSnapshotUri, "-ns1:GetSnapshotUri", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetSnapshotUri(soap_tmp___ns1__GetSnapshotUri.ns1__GetSnapshotUri, ns1__GetSnapshotUriResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetSnapshotUriResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetSnapshotUriResponse.soap_put(soap, "ns1:GetSnapshotUriResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetSnapshotUriResponse.soap_put(soap, "ns1:GetSnapshotUriResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetVideoSourceModes(Media2BindingService *soap)
{	struct __ns1__GetVideoSourceModes soap_tmp___ns1__GetVideoSourceModes;
	_ns1__GetVideoSourceModesResponse ns1__GetVideoSourceModesResponse;
	ns1__GetVideoSourceModesResponse.soap_default(soap);
	soap_default___ns1__GetVideoSourceModes(soap, &soap_tmp___ns1__GetVideoSourceModes);
	if (!soap_get___ns1__GetVideoSourceModes(soap, &soap_tmp___ns1__GetVideoSourceModes, "-ns1:GetVideoSourceModes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetVideoSourceModes(soap_tmp___ns1__GetVideoSourceModes.ns1__GetVideoSourceModes, ns1__GetVideoSourceModesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetVideoSourceModesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetVideoSourceModesResponse.soap_put(soap, "ns1:GetVideoSourceModesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetVideoSourceModesResponse.soap_put(soap, "ns1:GetVideoSourceModesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetVideoSourceMode(Media2BindingService *soap)
{	struct __ns1__SetVideoSourceMode soap_tmp___ns1__SetVideoSourceMode;
	_ns1__SetVideoSourceModeResponse ns1__SetVideoSourceModeResponse;
	ns1__SetVideoSourceModeResponse.soap_default(soap);
	soap_default___ns1__SetVideoSourceMode(soap, &soap_tmp___ns1__SetVideoSourceMode);
	if (!soap_get___ns1__SetVideoSourceMode(soap, &soap_tmp___ns1__SetVideoSourceMode, "-ns1:SetVideoSourceMode", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetVideoSourceMode(soap_tmp___ns1__SetVideoSourceMode.ns1__SetVideoSourceMode, ns1__SetVideoSourceModeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__SetVideoSourceModeResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SetVideoSourceModeResponse.soap_put(soap, "ns1:SetVideoSourceModeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SetVideoSourceModeResponse.soap_put(soap, "ns1:SetVideoSourceModeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetOSDs(Media2BindingService *soap)
{	struct __ns1__GetOSDs soap_tmp___ns1__GetOSDs;
	_ns1__GetOSDsResponse ns1__GetOSDsResponse;
	ns1__GetOSDsResponse.soap_default(soap);
	soap_default___ns1__GetOSDs(soap, &soap_tmp___ns1__GetOSDs);
	if (!soap_get___ns1__GetOSDs(soap, &soap_tmp___ns1__GetOSDs, "-ns1:GetOSDs", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetOSDs(soap_tmp___ns1__GetOSDs.ns1__GetOSDs, ns1__GetOSDsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetOSDsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetOSDsResponse.soap_put(soap, "ns1:GetOSDsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetOSDsResponse.soap_put(soap, "ns1:GetOSDsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetOSDOptions(Media2BindingService *soap)
{	struct __ns1__GetOSDOptions soap_tmp___ns1__GetOSDOptions;
	_ns1__GetOSDOptionsResponse ns1__GetOSDOptionsResponse;
	ns1__GetOSDOptionsResponse.soap_default(soap);
	soap_default___ns1__GetOSDOptions(soap, &soap_tmp___ns1__GetOSDOptions);
	if (!soap_get___ns1__GetOSDOptions(soap, &soap_tmp___ns1__GetOSDOptions, "-ns1:GetOSDOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetOSDOptions(soap_tmp___ns1__GetOSDOptions.ns1__GetOSDOptions, ns1__GetOSDOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetOSDOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetOSDOptionsResponse.soap_put(soap, "ns1:GetOSDOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetOSDOptionsResponse.soap_put(soap, "ns1:GetOSDOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetOSD(Media2BindingService *soap)
{	struct __ns1__SetOSD soap_tmp___ns1__SetOSD;
	struct __ns1__SetOSDResponse soap_tmp___ns1__SetOSDResponse;
	soap_default___ns1__SetOSDResponse(soap, &soap_tmp___ns1__SetOSDResponse);
	soap_default___ns1__SetOSD(soap, &soap_tmp___ns1__SetOSD);
	if (!soap_get___ns1__SetOSD(soap, &soap_tmp___ns1__SetOSD, "-ns1:SetOSD", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetOSD(soap_tmp___ns1__SetOSD.ns1__SetOSD, soap_tmp___ns1__SetOSDResponse.ns1__SetOSDResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetOSDResponse(soap, &soap_tmp___ns1__SetOSDResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetOSDResponse(soap, &soap_tmp___ns1__SetOSDResponse, "-ns1:SetOSDResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetOSDResponse(soap, &soap_tmp___ns1__SetOSDResponse, "-ns1:SetOSDResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__CreateOSD(Media2BindingService *soap)
{	struct __ns1__CreateOSD soap_tmp___ns1__CreateOSD;
	_ns1__CreateOSDResponse ns1__CreateOSDResponse;
	ns1__CreateOSDResponse.soap_default(soap);
	soap_default___ns1__CreateOSD(soap, &soap_tmp___ns1__CreateOSD);
	if (!soap_get___ns1__CreateOSD(soap, &soap_tmp___ns1__CreateOSD, "-ns1:CreateOSD", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CreateOSD(soap_tmp___ns1__CreateOSD.ns1__CreateOSD, ns1__CreateOSDResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__CreateOSDResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CreateOSDResponse.soap_put(soap, "ns1:CreateOSDResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CreateOSDResponse.soap_put(soap, "ns1:CreateOSDResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__DeleteOSD(Media2BindingService *soap)
{	struct __ns1__DeleteOSD soap_tmp___ns1__DeleteOSD;
	struct __ns1__DeleteOSDResponse soap_tmp___ns1__DeleteOSDResponse;
	soap_default___ns1__DeleteOSDResponse(soap, &soap_tmp___ns1__DeleteOSDResponse);
	soap_default___ns1__DeleteOSD(soap, &soap_tmp___ns1__DeleteOSD);
	if (!soap_get___ns1__DeleteOSD(soap, &soap_tmp___ns1__DeleteOSD, "-ns1:DeleteOSD", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->DeleteOSD(soap_tmp___ns1__DeleteOSD.ns1__DeleteOSD, soap_tmp___ns1__DeleteOSDResponse.ns1__DeleteOSDResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteOSDResponse(soap, &soap_tmp___ns1__DeleteOSDResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteOSDResponse(soap, &soap_tmp___ns1__DeleteOSDResponse, "-ns1:DeleteOSDResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteOSDResponse(soap, &soap_tmp___ns1__DeleteOSDResponse, "-ns1:DeleteOSDResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetMasks(Media2BindingService *soap)
{	struct __ns1__GetMasks soap_tmp___ns1__GetMasks;
	_ns1__GetMasksResponse ns1__GetMasksResponse;
	ns1__GetMasksResponse.soap_default(soap);
	soap_default___ns1__GetMasks(soap, &soap_tmp___ns1__GetMasks);
	if (!soap_get___ns1__GetMasks(soap, &soap_tmp___ns1__GetMasks, "-ns1:GetMasks", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetMasks(soap_tmp___ns1__GetMasks.ns1__GetMasks, ns1__GetMasksResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetMasksResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetMasksResponse.soap_put(soap, "ns1:GetMasksResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetMasksResponse.soap_put(soap, "ns1:GetMasksResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__GetMaskOptions(Media2BindingService *soap)
{	struct __ns1__GetMaskOptions soap_tmp___ns1__GetMaskOptions;
	_ns1__GetMaskOptionsResponse ns1__GetMaskOptionsResponse;
	ns1__GetMaskOptionsResponse.soap_default(soap);
	soap_default___ns1__GetMaskOptions(soap, &soap_tmp___ns1__GetMaskOptions);
	if (!soap_get___ns1__GetMaskOptions(soap, &soap_tmp___ns1__GetMaskOptions, "-ns1:GetMaskOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetMaskOptions(soap_tmp___ns1__GetMaskOptions.ns1__GetMaskOptions, ns1__GetMaskOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetMaskOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetMaskOptionsResponse.soap_put(soap, "ns1:GetMaskOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetMaskOptionsResponse.soap_put(soap, "ns1:GetMaskOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__SetMask(Media2BindingService *soap)
{	struct __ns1__SetMask soap_tmp___ns1__SetMask;
	struct __ns1__SetMaskResponse soap_tmp___ns1__SetMaskResponse;
	soap_default___ns1__SetMaskResponse(soap, &soap_tmp___ns1__SetMaskResponse);
	soap_default___ns1__SetMask(soap, &soap_tmp___ns1__SetMask);
	if (!soap_get___ns1__SetMask(soap, &soap_tmp___ns1__SetMask, "-ns1:SetMask", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetMask(soap_tmp___ns1__SetMask.ns1__SetMask, soap_tmp___ns1__SetMaskResponse.ns1__SetMaskResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetMaskResponse(soap, &soap_tmp___ns1__SetMaskResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetMaskResponse(soap, &soap_tmp___ns1__SetMaskResponse, "-ns1:SetMaskResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetMaskResponse(soap, &soap_tmp___ns1__SetMaskResponse, "-ns1:SetMaskResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__CreateMask(Media2BindingService *soap)
{	struct __ns1__CreateMask soap_tmp___ns1__CreateMask;
	_ns1__CreateMaskResponse ns1__CreateMaskResponse;
	ns1__CreateMaskResponse.soap_default(soap);
	soap_default___ns1__CreateMask(soap, &soap_tmp___ns1__CreateMask);
	if (!soap_get___ns1__CreateMask(soap, &soap_tmp___ns1__CreateMask, "-ns1:CreateMask", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CreateMask(soap_tmp___ns1__CreateMask.ns1__CreateMask, ns1__CreateMaskResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__CreateMaskResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CreateMaskResponse.soap_put(soap, "ns1:CreateMaskResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CreateMaskResponse.soap_put(soap, "ns1:CreateMaskResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__DeleteMask(Media2BindingService *soap)
{	struct __ns1__DeleteMask soap_tmp___ns1__DeleteMask;
	struct __ns1__DeleteMaskResponse soap_tmp___ns1__DeleteMaskResponse;
	soap_default___ns1__DeleteMaskResponse(soap, &soap_tmp___ns1__DeleteMaskResponse);
	soap_default___ns1__DeleteMask(soap, &soap_tmp___ns1__DeleteMask);
	if (!soap_get___ns1__DeleteMask(soap, &soap_tmp___ns1__DeleteMask, "-ns1:DeleteMask", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->DeleteMask(soap_tmp___ns1__DeleteMask.ns1__DeleteMask, soap_tmp___ns1__DeleteMaskResponse.ns1__DeleteMaskResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteMaskResponse(soap, &soap_tmp___ns1__DeleteMaskResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteMaskResponse(soap, &soap_tmp___ns1__DeleteMaskResponse, "-ns1:DeleteMaskResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteMaskResponse(soap, &soap_tmp___ns1__DeleteMaskResponse, "-ns1:DeleteMaskResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
